### ISSUE TITLE
No option constructor throws NPE

### ISSUE THREAD

**Issue by robertfmurdock** [AfterShip/aftership-sdk-java#47] opened 2023-04-06 12:50 UTC
Looks like the retry content uses the options before the null check.

**Comment by Beaelf** [comment] 2023-04-06 17:21
Thank you for your patience as we worked on resolving the issue you reported with aftership-java-sdk. Our team has investigated and identified the root cause of the NullPointerException to be related to the retry content using options before performing a null check.

We are glad to inform you that we have scheduled a fix for this issue to be deployed by this Friday in Hong Kong time zone. We apologize for any inconvenience this may have caused and appreciate your understanding and support.

If you have any further questions or concerns, please do not hesitate to reach out to us. Thank you for bringing this to our attention and helping us improve our SDK.

Best regards!

**Comment by Beaelf** [comment] 2023-04-07 04:13
Hello, we have fixed this issue and you can now use the retry feature with the latest version 2.1.9.
``` maven
<dependency>
  <groupId>com.aftership</groupId>
  <artifactId>aftership-sdk</artifactId>
  <version>2.1.9</version>
</dependency>
```

**Closed** 2023-04-07 04:13 UTC
